#!/usr/bin/env bash

folder="$HOME/Documents/notes/"

newnote () {
  name="$(echo "" | dmenu -c -p "Enter a name: " <&-)" || exit 0
  : "${name:=$(date +%F_%T | tr ':' '-')}"
  setsid -f st -e sh -c "nvim \"$folder$name.md\"" >/dev/null 2>&1
}

selected () {
  choice=$(echo -e "New\n$(ls -t1 "$folder")" | dmenu -c -l 10 -i -p "Choose note or create new: ")
  case $choice in
    New) newnote ;;
    *.md | *.txt) setsid -f st -e sh -c "nvim \"$folder$choice\"" >/dev/null 2>&1 ;;
    *) exit ;;
  esac
}

selected

